# Mysql数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://122.14.196.211:3306/guns?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: LFjmkj123$
    filters: wall,mergeStat

    # 连接池大小根据实际情况调整
    max-active: 20
    max-pool-prepared-statement-per-connection-size: 20
    data-source-name: guns

#多数据源的配置情况:
guns:
   muti-datasource:
     open: ture
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://122.14.196.211:3306/njhxcx?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
     username: root
     password: LFjmkj123$
     data-source-name: purchase